=== ArmandoSantiago/XMLSChema/raiz/src/salon.dtd
<!ELEMENT SALON (ALUMNO+) >
<!ELEMENT ALUMNO (NOMBRE, GENERO, FECHA_NAC, AMIGOS*, EDAD?, CARRERA?) >
<!ATTLIST ALUMNO COD CDATA #REQUIRED>
<!ELEMENT NOMBRE (#PCDATA) >
<!ELEMENT GENERO (#PCDATA) >
<!ELEMENT FECHA_NAC (#PCDATA) >
<!ELEMENT AMIGOS (#PCDATA) >
<!ELEMENT EDAD (#PCDATA) >
<!ELEMENT CARRERA (#PCDATA) >

=== ArmandoSantiago/XMLSChema/raiz/src/documento.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no" ?>
<!DOCTYPE SALON SYSTEM "salon.dtd">
<SALON>
    <ALUMNO COD="1">
        <NOMBRE>Azucena</NOMBRE>
        <AMIGOS>Armando</AMIGOS>
        <AMIGOS>Fernando</AMIGOS>
        <EDAD>22</EDAD>
        <CARRERA>Terapia fisica</CARRERA>
    </ALUMNO>
    <ALUMNO COD="1">
        <NOMBRE>Armando</NOMBRE>
        <AMIGOS>Azucena</AMIGOS>
        <AMIGOS>Omar</AMIGOS>
        <EDAD>21</EDAD>
        <CARRERA>Sistemas Informaticos</CARRERA>
    </ALUMNO>
</SALON>
